command-time-out: 360000
code-constructors-instrumentation-path: "/home/commun/infom125/sentinel-group/sentinel-experiments/src/main/java/be/unamur/snail/spoon/constructor_instrumentation"
project:
  name: "jackson-core"
  owner: "fasterxml"
  sub-project: ""
  show-project-logs: true
  package-prefix: "tools.jackson.core"
repo:
  url: "https://github.com/FasterXML/jackson-core.git"
  commit: "701cd6af465c586aa9b33e95294acde034bd17af"
  # ATTENTION de ne pas supprimer le dossier joularjx-results en instrumentant
  # un projet qui a été analysé auparavant => spécifier 2 target-dir différents
  # pour l'instrumentation et les mesures
  target-dir: "/home/commun/infom125/sentinel-group/repositories/"
  jdk: "17.0.10-tem"
  overwrite-clone: false
  overwrite-copy: true
environment:
  sdkman-init: "/etc/profile.d/sdkman.sh"
log:
  level: INFO
  directory: "/home/commun/infom125/sentinel-group/sentinel-experiments/logs/jackson-core/"
  also-log-to-console: true
  clear-previous-logs: true
execution-plan:
  test-command: "mvn clean test"
  ignore-failures: false
  ignore-spoon-failures: true
  num-test-runs: 200
  energy-measurements:
    warmup-duration-seconds: 300
    sleep-duration-seconds: 60
    tool: "joularjx"
    tool-version: "3.0.1"
    release-url: "https://github.com/joular/joularjx"
    tool-path: "/home/commun/infom125/sentinel-group/joularjx"
    import-config:
      scopes: ["app"]
      measurement-types: ["runtime", "total"]
      monitoring-types: ["calltrees", "methods"]
backend:
  mode: dev
  server-host: localhost
  server-port: 8080
  server-timeout-seconds: 240
  server-log-path: "/tmp/sentinel-backend.log"
  server-ready-path: "/tmp/backend-ready"
  endpoint: "/api/v2/constructor-contexts"
  # dev-specific
  server-path: "/home/commun/infom125/sentinel-group/sentinel-backend/"
  nb-check-server-start: 25
  # prod-specific
  ssh-user: "jmaquoi"
  ssh-host: "ava.info.unamur.be"